name: m2_sd2022_env
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2024.2.2
  - libffi=3.4.2
  - libsqlite=3.45.2
  - libzlib=1.2.13
  - ncurses=6.4.20240210
  - openssl=3.2.1
  - pip=24.0
  - python=3.10.14
  - readline=8.2
  - setuptools=69.2.0
  - tk=8.6.13
  - wheel=0.43.0
  - xz=5.2.6
  - pip:
      - accelerate==0.27.2
      - appnope==0.1.4
      - asttokens==2.4.1
      - certifi==2024.2.2
      - charset-normalizer==3.3.2
      - comm==0.2.2
      - contourpy==1.2.1
      - cycler==0.12.1
      - debugpy==1.8.1
      - decorator==5.1.1
      - exceptiongroup==1.2.0
      - executing==2.0.1
      - filelock==3.13.3
      - fonttools==4.50.0
      - fsspec==2024.3.1
      - huggingface-hub==0.22.2
      - idna==3.6
      - ipykernel==6.29.2
      - ipython==8.21.0
      - jedi==0.19.1
      - jinja2==3.1.3
      - jupyter-client==8.6.1
      - jupyter-core==5.7.2
      - kiwisolver==1.4.5
      - lightning-utilities==0.11.2
      - markupsafe==2.1.5
      - matplotlib==3.8.4
      - matplotlib-inline==0.1.6
      - mpmath==1.3.0
      - nest-asyncio==1.6.0
      - networkx==3.2.1
      - numpy==1.26.4
      - packaging==24.0
      - pandas==2.2.1
      - parso==0.8.3
      - pexpect==4.9.0
      - pillow==10.3.0
      - platformdirs==4.2.0
      - prompt-toolkit==3.0.43
      - psutil==5.9.8
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pygments==2.17.2
      - pyparsing==3.1.2
      - python-dateutil==2.9.0.post0
      - pytz==2024.1
      - pyyaml==6.0.1
      - pyzmq==25.1.2
      - requests==2.31.0
      - safetensors==0.4.2
      - scipy==1.13.0
      - six==1.16.0
      - stack-data==0.6.3
      - sympy==1.12
      - torch==2.2.0
      - torchmetrics==1.3.2
      - torchvision==0.17.0
      - tornado==6.4
      - tqdm==4.66.2
      - traitlets==5.14.2
      - typing==3.7.4.3
      - typing-extensions==4.10.0
      - tzdata==2024.1
      - urllib3==2.2.1
      - wcwidth==0.2.13
